microlang:
	gf -make ../lab2/grammar/english/MicroLangEng.gf ../lab2/grammar/functor/MicroLangFunctorSwe.gf

minilang:
	gf -make ../lab2/grammar/english/MiniLangEng.gf ../lab2/grammar/functor/MiniLangFunctorSwe.gf

query:
	gf -make QueryEng.gf QuerySwe.gf

draw:
	gf -make DrawEng.gf DrawSwe.gf DrawFin.gf DrawGer.gf



